### PR TITLE
Audio Player changes from Avoke Team

### PR DESCRIPTION
**Pull request by surender-india**
Hi Drew

During integrating vaadin audio player into Avoke Project, we have modified the vaadin audio player . 
On modification, we have fix the bugs with respective commits. 
Also add few more js api for audio player. 
Please review the changes and let me know if you want more information.

Thanks and regards
Surender Singh
Avoke Team

### CODE REVIEW

**Comment by TatuLund** [comment]
@surender-india your modifications are based on too old version of the AudioPlayer, thus there are plenty of merge conflict. Also I noticed that some of the modifications you propose are already in the newer version. For example, I think your commit f542ca0 is already obsolete. So these changes cannot be merged as is.

**Comment by mthome** [comment]
I've asked Surender to update and resubmit

**Comment by drewharvey** [comment]
@surender-india should I ignore/close this PR?  I see that you have another - #12 .

**Comment by TatuLund** [comment]
Yes, this one should be ignored and closed in favor of #12

**Comment by drewharvey** [comment]
Closing, replaced by #12.

**Pull request closed without merging**
